name: Upload to itch.io
on:
  push:
    branches:
      - release


env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  ITCH_USERNAME: spel16
  ITCH_GAME_ID: stalemate
jobs:
  buildWebGL:
    name: Build for WebGL ðŸ–¥ï¸
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          channel:
            - web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Test
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}      
        with:
          targetPlatform: WebGL

      - uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/${{ matrix.template }}
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
          #discord notifies testers     
      #    avatar_url: ${{ secrets.AVATAR_URL }}
  # .github/workflows/main.yml
  # buildForAndroidPlatform:
  #   name: Build For Android Platform
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       with:
  #         path: Library
  #         key: Library-Android
  #     - uses: game-ci/unity-builder@v2
  #       with:
  #         targetPlatform: Android
  #         androidAppBundle: true
  #         androidKeystoreName: user.keystore
  #         androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
  #         androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
  #         androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
  #         androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: build-Android
  #         path: build/Android

  # releaseToGooglePlay:
  #   name: Release to the Google Play Store
  #   runs-on: ubuntu-latest
  #   needs: buildForAndroidPlatform
  #   env:
  #     GOOGLE_PLAY_KEY_FILE: ${{ secrets.GOOGLE_PLAY_KEY_FILE }}
  #     GOOGLE_PLAY_KEY_FILE_PATH: ${{ format('{0}/fastlane/google-fastlane.json', github.workspace) }}
  #     ANDROID_BUILD_FILE_PATH: ${{ format('{0}/build/Android/Android.aab', github.workspace) }}
  #     ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
  #     - name: Download Android Artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build-Android
  #         path: build/Android
  #     - name: Add Authentication
  #       run: echo "$GOOGLE_PLAY_KEY_FILE" > $GOOGLE_PLAY_KEY_FILE_PATH
  #     - name: Install Fastlane
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7.2
  #         bundler-cache: true
  #     - name: Upload to Google Play beta
  #       uses: maierj/fastlane-action@v2.0.1
  #       with:
  #         lane: 'android beta'
  #     - name: Cleanup to avoid storage limit
  #       if: always()
  #       uses: geekyeggo/delete-artifact@v1
  #       with:
  #         name: build-Android   
  buildWindows:
    name: Build for Windows ðŸ–¥ï¸
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          channel:
            - win
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} 
        with:
          targetPlatform: StandaloneWindows64

      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows 
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/${{ matrix.template }}
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
  # toDiscord:
  #   name: Upload discord
  #   needs: [releaseToGooglePlay, buildWindows, buildWebGL]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: sarisia/actions-status-discord@v1.8.6
  #       with:
  #         webhook: ${{ secrets.DISCORD_WEBHOOK }}
  #         nodetail: true
  #         title: "***New Update on itch and playstore:*** https://tycro-games.itch.io/lunar-voyage-moon-colonization https://play.google.com/store/apps/details?id=com.TycroGames.TAI"
  #         description: ${{github.event.head_commit.message }}
  #       # image: ${{ secrets.EMBED_IMAGE }}
  #         color: 0xffffff
  #         username: Your friendly spiderman     